version: "3.8"

services:
  frontend:
    container_name: react-frontend
    image: sega1294/frontend-docker:latest@sha256:5474f90bd45ef7e0074d4a8f194457a62191a5a9bf6f6593ddfb0e9f7a1db9f1
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    restart: always
  backend:
    container_name: flask-backend
    image: sega1294/backend-docker:latest@sha256:429d7e9383fd2b742a0d72dec759f78a4968b457076955b8c2cbe2275583e3c0
    volumes:
      - /usr/share/caster/log/:/code/caster/log/
    ports:
      - 5000:5000
    devices:
      - "/dev/ttyACM0"
    restart: always
  caster:
    container_name: caster-server
    image: sega1294/caster-server:latest@sha256:fe0e120b4cfafa61ef11c1e0a48add138292be16b5c727d0ca24680325db7451
    ports:
      - 2101:2101
    devices:
      - "/dev/ttyACM0"
    restart: always
